### ISSUE TITLE
Maven repo

### ISSUE THREAD

**Issue by tomas-pluskal** [PRIDE-Utilities/jmzml#18]
Which maven repository has the latest jmzml version (1.7.5)?
http://www.ebi.ac.uk/~maven/m2repo doesn't have it
http://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo is dead

**Comment by ypriverol** [comment]
Dear @tomas-pluskal the EBI maven repositories are unavailable due a general maintenance of the EBI infrastructure. I will be back to you when this issue get solve.

**Comment by tomas-pluskal** [comment]
Honestly, it looks quite unprofessional.. I don't know what kind of maintenance is going on, but an organization of EBI scale should be able to manage that without taking its services down. If maintaining a maven server is too much, why don't you just deploy everything to the Sonatype OSS repo?

**Comment by ypriverol** [comment]
I fully agree with you. Is actually more complicated than that:
 1- This is the official announcement from last week: http://www.ebi.ac.uk/about/news/service-news/maintaining-our-data-centres it is also related with some UK laws. 
 2- After the shutdown of the last week one of the major storage systems became unavailable and
      now the IT is working to fix it. 
We hope to be back soon this week and I can guaranty you that in the future we will have a batter plan and deploy some of our libraries in multiple places. 

Thanks for your understand @tomas-pluskal !!!

**Comment by fcyu** [comment]
Dear @ypriverol 

May I give a suggestion? What about publish the project to the publish maven repository (please refer to [http://search.maven.org/](url) or [http://mvnrepository.com/](url)). It is more robust and importing projects is much easier.

Thanks.

**Comment by ypriverol** [comment]
Dear @fcyu I will review what is the best option and we will try to implement it. Thanks for your suggestion

**Comment by ypriverol** [comment]
Daer @tomas-pluskal @fcyu All the repos are now back. Please test it and let me know if everything is going well. 

Regards 
Yasset
