### ISSUE TITLE
Maven repository incorrect url

### ISSUE THREAD

**Issue by jbradbury** [PRIDE-Utilities/jmzml#21]
The URL tag in the maven repository in the README.md is incorrect and my project would not compile. Once I changed it to:
`<url>http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/</url>`
I was able to compile

**Comment by tomas-pluskal** [comment]
At the moment the ```http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/``` repository seems to be down, too. 

<img width="856" alt="screen shot 2019-01-31 at 13 36 03" src="https://user-images.githubusercontent.com/1796692/52076674-300f3500-255d-11e9-96a2-aa6c7acb8e5b.png">

**Comment by tomas-pluskal** [comment]
@ypriverol What is the status of the EBI maven repo?

**Comment by ypriverol** [comment]
Hi @tomas-pluskal the current maven URL is this one: 

```maven
<!-- EBI repo -->
<repository>
    <id>nexus-ebi-release-repo</id>
    <url>http://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/</url>
</repository>

<!-- EBI SNAPSHOT repo -->
<snapshotRepository>
   <id>nexus-ebi-snapshots-repo</id>
   <url>http://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-snapshots/</url>
</snapshotRepository> 
```

**Comment by ypriverol** [comment]
If this work for you I will close the issue.

**Comment by tomas-pluskal** [comment]
Hi @ypriverol , the repo does not work, it redirects to the failure page I screenshot above. Try yourself by clicking here: http://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/

**Comment by ypriverol** [comment]
You are right nexus is down. I will take care of this and go back to you. I was confused because the original URL you posted is not the rigth one.

**Comment by ypriverol** [comment]
Nexus is up now. Thanks, @tomas-pluskal and let me know if you have any issue.

**Comment by tomas-pluskal** [comment]
Thanks! I'll file a separate issue.

**Comment by ypriverol** [comment]
@tomas-pluskal Would be great if you perform the benchmark that you did before with the current version. Thanks in advance.
