### ISSUE TITLE
missing chardet dependency

### ISSUE THREAD

**Issue by tomas-pluskal** [PRIDE-Utilities/jmzml#22]
Hi,
I tried jmzml 1.7.11, but it depends on xxindex 0.23, which itself has this dependency:
````
		<dependency>
			<groupId>org.mozilla.intl</groupId>
			<artifactId>chardet</artifactId>
			<version>1.0</version>
		</dependency>
````
But the chardet dependency is nowhere to be found.

**Comment by ypriverol** [comment]
Interesting. I see the the dependency here: https://mvnrepository.com/artifact/org.mozilla.intl/chardet/1.0 What d you think?

**Comment by tomas-pluskal** [comment]
Okay, it seems to be here:
https://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/org/
But not here:
https://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/org/
In the previous issue discussion you said the official repo is the "Tools" repo.

**Comment by ypriverol** [comment]
I will push the dependency to the new repo.

**Comment by ypriverol** [comment]
Hi @tomas-pluskal I have been investigating how we can move into nexus the library. Still no solution .. will keep you updated.

**Comment by tomas-pluskal** [comment]
Why don't you deposit your public jars into Maven Central instead? It seems there have been recurring issues with the EBI maven repository..

**Comment by ypriverol** [comment]
We have this discussion long time ago. I will go back to that after we fix the current problem.

**Comment by ypriverol** [comment]
@tomas-pluskal @julianu can you try now. Let me know if it works.

**Comment by tomas-pluskal** [comment]
Seems to be working fine now.

**Comment by ypriverol** [comment]
Thanks for reporting the issue. I will try to see how we can sync nexus to maven central. Would be great if you can do some testing with the new library (performance.)
