### ISSUE TITLE
EBI maven repo down again

### ISSUE THREAD

**Issue by tomas-pluskal** [PRIDE-Utilities/jmzml#23]
https://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo

<img width="853" alt="screen shot 2019-02-02 at 16 00 21" src="https://user-images.githubusercontent.com/1796692/52169290-b2d1f480-2703-11e9-847a-bb4bd134bba2.png">

**Comment by tomas-pluskal** [comment]
Same with https://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/

**Comment by ypriverol** [comment]
@tomas-pluskal the EBI in trying to solve some major infrastructure issues.

**Comment by tomas-pluskal** [comment]
...Brexit?

**Comment by ypriverol** [comment]
One of our datacenters is down. No email, etc.. I don't really know how much is affected. This make more clear that we should move to Maven Central. I will start doing the migration this month.

**Comment by tomas-pluskal** [comment]
Great idea.

**Comment by tomas-pluskal** [comment]
Any ETA on the resurrection of the maven repo?

**Comment by ypriverol** [comment]
No yet. I will be back to this issue when everything is solved.

**Comment by noedelta** [comment]
Hi Tomáš and Yasset,

I have been able to restart nexus after the cooling failure in one of the data centres. Hopefully it will stay alive again.

Regards,

Noe

Noemi del Toro Ayllón
Software Engineer 
Molecular Interactions Team
European Molecular Biology Laboratory
European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom

**Comment by tomas-pluskal** [comment]
Awesome, thanks!

**Comment by ypriverol** [comment]
Still is pending the missing dependency. We will solve the issue soon.
